apiVersion: apps/v1
kind: Deployment
metadata:
  name: elad-assign
  namespace: elad-assign
  labels:
    app: elad-assign
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elad-assign
  template:
    metadata:
      labels:
        app: elad-assign
    spec:
      containers:
      - name: elad-assign
        image: eilon01/elad_assign:1.0
        ports:
        - containerPort: 5000
